trigger: none

parameters:
  - name: deployToDevelopmentEnvironment
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: true
  - name: workItemId
    displayName: "The id of the work item (This will be used in the environment name)"
    type: string
    default: '12345'

resources:
  repositories:
    - repository: PipelineCommon
      name: DEFRA-DEVOPS-COMMON/Defra.Pipeline.Common
      type: git
    - repository: GIO_DATA_PLATFORM
      name: DEFRA-Common-Platform-Improvements/GIO_DATA_PLATFORM
      type: git
      ref: feat/ephemeral-support

extends:
  template: /templates/pipelines/common-infrastructure-deploy.yaml@PipelineCommon
  parameters:
    variableFiles:
      - /src/config/catalogue/vars/ephemeral.yaml@GIO_DATA_PLATFORM
    projectName: Purview Data Catalogue
    deployFromFeature: ${{ parameters.deployToDevelopmentEnvironment }}
    privateAgentName: DEFRA-COMMON-windows2022-SSV3
    environments:
      - name: 'Ephemeral'
        developmentEnvironment: True
        useDevelopmentEnvironmentForValidationOnly: False
        azureRegions:
          primary: NorthEurope
        serviceConnection: AZD-CPR-DEV1
        privateAgentName: DEFRA-COMMON-windows2022-SSV3
    groupedTemplates:
      - name: Purview_Ephemeral_infra
        templates:
          - name: purview
            isDeployToSecondaryRegions: false
            path: src/features/catalogue/infra
            type: bicep
            parameterFilePath: src/features/catalogue/infra
            scope: "Resource Group"
            resourceGroupName: $(resourceGroup)
            postDeployScriptsList:
              - displayName: Add Permission to ephemeral Group
                type: AzurePowerShell
                inlineScript: |
                  Install-Module -Name Az.Purview -Force
                  Import-Module -Name Az.Purview
                  Add-AzPurviewAccountRootCollectionAdmin -AccountName $(ephemeralName) -ResourceGroupName $(resourceGroup) -ObjectId $(adminGroupId)
              - displayName: 'Configure Collections'
                scriptPath: 'src/infrastructure/scripts/PowerShell/Scripts/Purview/ConfigureCollections.ps1'
                type: AzurePowerShell
                scriptArguments: '-ConfigFilePath "$(Build.SourcesDirectory)/GIO_DATA_PLATFORM/src/config/catalogue/Extract/Collections/collections.json" -ImportConfigPath "$(Build.SourcesDirectory)/GIO_DATA_PLATFORM/src/config/catalogue/importConfig.json" -AccountName $(ephemeralName)'
              - displayName: 'Configure Collection Permissions'
                scriptPath: 'src/infrastructure/scripts/PowerShell/Scripts/Purview/ConfigureCollectionPermissions.ps1'
                type: AzurePowerShell
                scriptArguments: '-ConfigFilePath "$(Build.SourcesDirectory)/GIO_DATA_PLATFORM/src/config/catalogue/Extract/Collections/Permissions/$(scriptEnvironment)" -AccountName $(ephemeralName)'  
              - displayName: 'Configure Classifications'
                scriptPath: 'src/infrastructure/scripts/PowerShell/Scripts/Purview/ConfigureClassifications.ps1'
                type: AzurePowerShell
                scriptArguments: '-ConfigFilePath "$(Build.SourcesDirectory)/GIO_DATA_PLATFORM/src/config/catalogue/Extract/TypeDefinitions/classifications.json" -AccountName $(ephemeralName)'