name: $(BuildID)

parameters:
  - name: whatIf
    displayName: PowerShell WhatIf Comparison
    type: boolean
    default: true

  - name: deploy
    displayName: "Deployment"
    type: boolean
    default: false

  - name: region
    displayName: "Region"
    type: string
    default: uksouth
    values:
      - uksouth

  - name: featureBranch
    displayName: "GIO Feature Branch to extract to"
    type: string
    default: feat/branchName

pool: DEFRA-COMMON-windows2022-SSV3

trigger: none
pr: none

resources:
  repositories:
    - repository: PipelineCommon
      name: DEFRA-DEVOPS-COMMON/Defra.Pipeline.Common
      type: git
      ref: main
    - repository: GIO_DATA_PLATFORM
      name: DEFRA-Common-Platform-Improvements/GIO_DATA_PLATFORM
      type: git
      ref: ${{ parameters.featureBranch }}

variables:
  gioRepo: $[ resources.repositories.GIO_DATA_PLATFORM.ref ]
  targetRepoUrl: $[ resources.repositories.GIO_DATA_PLATFORM.url ]

extends:
  template: /templates/pipelines/common-scripts-deploy.yaml@PipelineCommon
  parameters:
    additionalRepositories:
      -  GIO_DATA_PLATFORM
    variableFiles:
      - /vars/common.yaml@GIO_DATA_PLATFORM
      - /vars/{environment}.uksouth.yaml@GIO_DATA_PLATFORM
    environments:
      - name: 'DP_DEV'
        azureRegions:
          primary: uksouth
        developmentEnvironment: true
        deploymentBranches:
          - '*'
        serviceConnection: AZD-CPR-DEV1
    scriptsList:   
       - displayName: 'Extract Purview Customisations into local Branch'
         scriptPath: 'src/infrastructure/scripts/PowerShell/Scripts/Purview/ExtractPurviewCustomisations.ps1'
         type: AzurePowerShell
         scriptArguments: '-TargetRepoUrl $(targetRepoUrl) -RootRepoPath "$(Build.SourcesDirectory)\GIO_DATA_PLATFORM" -FolderPath "$(Build.SourcesDirectory)\GIO_DATA_PLATFORM/src/config/catalogue/Extract" -ExportSettings "$(Build.SourcesDirectory)/GIO_DATA_PLATFORM/src/config/catalogue/exportConfig.json" -AccountName "$(scriptEnvironment)$(parent-project)$(nc-function-application)PV$(subscriptionNumber)$(regionNumber)01" -QueuedBy "$(Build.QueuedBy)" -SourceBranch "$(gioRepo)" -AdoAccessToken $(System.AccessToken) -AdoProject $(System.TeamProject) -AdoAccountUrl $(System.CollectionUri)'
